services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: "chatbot-reserv"
    container_name: ${PGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_DATA}
    expose:
      - "3401"
    volumes:
      - chatbot_volume:${POSTGRES_DATA}
      - ./db/data:/data
    ports:
      - "3401:3401"
    restart: unless-stopped
    command: -p 3401

  api:
    extends:
      file: ./api/api-docker-compose.yml
      service: api
      env_file: ./api/.env
    volumes:
      - rasa_volume:/chatbot

  rasa-core:
    extends:
      file: ./chatbot/rasa-docker-compose.yml
      env_file: ./chatbot/.env
      service: rasa-core
    volumes:
      - db_data:/db/data

  duckling:
    extends:
      file: ./chatbot/rasa-docker-compose.yml
      service: duckling
      env_file: ./chatbot/.env

  actions-server:
    extends:
      file: ./chatbot/rasa-docker-compose.yml
      service: actions-server
      env_file: ./chatbot/.env
  telegram:
    extends:
      file: ./telegram_bot/telegram-docker-compose.yml
      service: telegram
      env_file: ./telegram_bot/.env
  backend-chatbox:
    extends:
      file: ./chatbox-webapp/chatbox-docker-compose.yml
      service: backend-chatbox
  frontend-chatbox:
    extends:
      file: ./chatbox-webapp/chatbox-docker-compose.yml
      service: frontend-chatbox
volumes:
  chatbot_volume:
    external: false
  rasa_volume:
    driver: local
    driver_opts:
      device: "./chatbot"
      o: bind
      type: none
  db_data:
    driver: local
    driver_opts:
      device: "./db/data"
      o: bind
      type: none