services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: "chatbot-reserv"
    container_name: ${PGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_DATA}
    volumes:
      - chatbot_volume:${POSTGRES_DATA}
    ports:
      - "3401:3401"
    restart: unless-stopped
  # api:
  # chatbot:

  